---
title: "lab3"
author: "Полянская Полина Алексеевна"
format:   
  md:
    output-file: README.md
editor_options: 
  chunk_output_type: inline
---

Анализ данных сетевого трафика при помощи библиотеки
Arrow

## Цель

1. Изучить возможности технологии Apache Arrow для обработки и анализа больших данных \n
2. Получить навыки применения Arrow совместно с языком программирования R \n
3. Получить навыки анализа метаинфомации о сетевом трафике \n
4. Получить навыки применения облачных технологий хранения, подготовки и анализа данных: Yandex Object Storage, Rstudio Server. \n

## Исходные данные

1.  Ноутбук с ОС Windows 10
2.  RStudio
3.  Yandex Cloud
4.  Библиотека Arrow
5.  RStudio Server

## Задание 

Используя язык программирования R, библиотеку arrow
и облачную IDE Rstudio Server, развернутую в Yandex
Cloud, выполнить задания и составить отчет.

## Задачи

1. Найдите утечку данных из Вашей сети \n
2. Надите утечку данных 2  \n
3. Надите утечку данных 3 \n

## Ход работы

### Шаг 0. Настройка окружения. 

Смена прав на доступ к файлу ключа.
```{}
chmod =600 ~/key_th_pr3/rstudio.key
```

Подключение через SSH.
```{}
ssh -i ~/key_th_pr3/rstudio.key -L 8787:127.0.0.1:8787 userNN@62.84.123.211
```
```{}
NN - номер юзера
```

Смена пароля.
```{}
passwd
```

### Шаг 1. Импорт данных

### Шаг 2. Обработка данных

## Оценка результатов

...

## Вывод

...
